from .google_registration import GoogleRegisterView
from .login_view import LoginUserView
from .registration_view import RegisterUserView
from .google_login import GoogleLoginUserView
from .user_detail import UserDetailView
from .recommended_users import RecommendedUsersView
from .follow import FollowView
from .search import SearchUsersView
from .history import HistorySearchView
from .user2fa import TwoFAView
from .update import UpdateUserText
from .update import UpdateUserAvatar
from .reset_password import UpdatePassword